import openpyxl
from openpyxl.styles import Font, PatternFill
from datetime import datetime, timedelta

# Create a new workbook
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Faculty"

# Define headers
# Note: FacultyID is AUTO-GENERATED (PICT-FAC-XXX format), so not needed in Excel
headers = ["Name", "Email", "Mobile", "Department", "Profession", "Valid Till"]

# Add header row with formatting
header_fill = PatternFill(start_color="0e7490", end_color="0e7490", fill_type="solid")
header_font = Font(color="FFFFFF", bold=True)

for col, header in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col)
    cell.value = header
    cell.fill = header_fill
    cell.font = header_font

# Add instruction row
instruction_fill = PatternFill(start_color="dbeafe", end_color="dbeafe", fill_type="solid")
instruction_font = Font(color="0c4a6e", bold=False, size=9)
instruction_cell = ws.cell(row=2, column=1)
instruction_cell.value = "IMPORTANT: Faculty ID (PICT-FAC-XXX) is AUTO-GENERATED. Just fill in the data below."
instruction_cell.fill = instruction_fill
instruction_cell.font = instruction_font
ws.merge_cells('A2:F2')

# Sample data for faculty
valid_till = (datetime.now() + timedelta(days=365)).strftime("%Y-%m-%d")
sample_data = [
    ["Dr. Rajesh Gupta", "rajesh.gupta@pict.edu", "9988776655", "Computer Science", "Professor", valid_till],
    ["Dr. Priya Sharma", "priya.sharma@pict.edu", "9988776656", "Electronics", "Associate Professor", valid_till],
    ["Dr. Amit Patel", "amit.patel@pict.edu", "9988776657", "Mechanical", "Assistant Professor", valid_till],
    ["Ms. Neha Singh", "neha.singh@pict.edu", "9988776658", "Civil", "Lecturer", valid_till],
    ["Dr. Vikram Desai", "vikram.desai@pict.edu", "9988776659", "Electrical", "Professor", valid_till],
]

# Add data rows
for row_idx, row_data in enumerate(sample_data, 3):
    for col_idx, value in enumerate(row_data, 1):
        cell = ws.cell(row=row_idx, column=col_idx)
        cell.value = value
        cell.alignment = openpyxl.styles.Alignment(horizontal="left", vertical="center")

# Adjust column widths
ws.column_dimensions['A'].width = 20
ws.column_dimensions['B'].width = 28
ws.column_dimensions['C'].width = 15
ws.column_dimensions['D'].width = 25
ws.column_dimensions['E'].width = 22
ws.column_dimensions['F'].width = 15

# Add notes at bottom
note_row = len(sample_data) + 4
notes = [
    "FORMAT GUIDE:",
    "• Name: Faculty name (Text)",
    "• Email: Faculty email address (must be valid email format)",
    "• Mobile: 10-digit mobile number without spaces or dashes",
    "• Department: Department name (e.g., Computer Science, Electronics, etc.)",
    "• Profession: Job title (e.g., Professor, Associate Professor, Assistant Professor, Lecturer)",
    "• Valid Till: Date until which pass is valid (YYYY-MM-DD format)",
    "",
    "IMPORTANT NOTES:",
    "✓ Faculty ID (PICT-FAC-XXX) is AUTOMATICALLY GENERATED by the system",
    "✓ No need to enter Faculty ID in any column - it will be generated",
    "✓ Duplicate emails or mobile numbers will be rejected",
    "✓ All fields are REQUIRED",
]

note_font = Font(color="0c4a6e", size=9, italic=True)
for offset, note in enumerate(notes):
    cell = ws.cell(row=note_row + offset, column=1)
    cell.value = note
    cell.font = note_font

# Save the file
output_path = "sample_excel_files/faculty_bulk_upload.xlsx"
wb.save(output_path)

print(f"✅ Faculty Excel file created: {output_path}")
print("\nFormat Guide:")
print("Column 1: Name (Faculty name - Text)")
print("Column 2: Email (Email address)")
print("Column 3: Mobile (10-digit mobile number)")
print("Column 4: Department (Department name)")
print("Column 5: Profession (Job title)")
print("Column 6: Valid Till (YYYY-MM-DD format)")
print("\nNOTE: Faculty ID (PICT-FAC-XXX) is AUTO-GENERATED by the system")
print(f"\n✅ Sample data: {len(sample_data)} faculty members added")
